language: cpp
sudo: required
dis: trusty

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install libboost-dev

env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release 

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - cmake ../
  - make -j$(nproc) 