language: cpp
sudo: required
dis: bionic

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release 

before_install:
  - sudo apt-get install -y zlib1g-dev libxml2-dev libminizip-dev

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - cmake ../ -DUSE_SYSTEM_LIBS=ON -DJEBOOK_SERVER_TEST=ON 
  - make -j$(nproc) 
  - make test